name: Cargo Release Build

on:
  release:
    types:
      - created

permissions:
    contents: write
      
jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            filename: coh3-scardoc-gen
          - os: windows-latest
            filename: coh3-scardoc-gen.exe

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build Release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: $$ {{ secrets.BG_RELEASE_SECRET }}
        files: |
            target/release/${{ matrix.filename }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
